import = [
  "~/.config/alacritty/keybindings.toml",
  "~/.config/alacritty/fonts.toml",
  "~/.config/alacritty/colors.toml"
]

live_config_reload = true
working_directory = "None"

[env]
TERM = "xterm-256color"

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" }
]

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
padding = { x = 0, y = 0 }
dimensions = { columns = 80, lines = 24 }
dynamic_padding = true
opacity = 1.5
decorations = "Full"
decorations_theme_variant = "None"
dynamic_title = true
startup_mode = "Windowed"
blur = false
