# Dracula
#---------
# 282A36 - Black
# 44475A - Dark Gray
# 50FA7B - Green
# 6272A4 - Blue
# 8BE9FD - Cyan
# BD93F9 - Purple
# F1FA8C - Yellow
# F8F8F2 - White
# FF5555 - Red
# FF79C6 - Magenta
# FFB86C - Orange

[colors.primary]
background = "#282A36"
foreground = "#F8F8F2"
bright_foreground = "#FFFFFF"

[colors.cursor]
text = "#282A36"
cursor = "#BD93F9"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.selection]
text = "CellForeground"
background = "#44475a"

[colors.normal]
black = "#21222c"
red = "#FF5555"
green = "#50FA7B"
yellow = "#F1FA8C"
blue = "#6272A4"
magenta = "#FF79C6"
cyan = "#8BE9FD"
white = "#F8F8F2"

[colors.bright]
black = "#6272a4"
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92df"
cyan = "#a4ffff"
white = "#ffffff"

[colors.search.matches]
foreground = "#44475a"
background = "#50fa7b"

[colors.search.focused_match]
foreground = "#44475a"
background = "#FFB86C"

[colors.footer_bar]
background = "#282A36"
foreground = "#f8f8f2"

[colors.hints.start]
foreground = "#282A36"
background = "#F1FA8C"

[colors.hints.end]
foreground = "#F1FA8C"
background = "#282A36"
