[font]
size = 20.0

[font.bold]
family = "Monaspace Radon"
style = "Bold"

[font.italic]
family = "Monaspace Krypton"
style = "Italic"

[font.normal]
family = "Monaspace Neon"
style = "Light"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0
