[font.bold]
family = "CaskaydiaMono Nerd Font"
# family = "Inconsolata"
# family = "Monaspace Neon"
style = "Regular"

[font.italic]
 family = "CaskaydiaMono Nerd Font"
# family = "Monaspace Neon"
# family = "Inconsolata"
style = "Italics"

[font.normal]
family = "CaskaydiaMono Nerd Font"
# family = "Monaspace Neon"
# family = "Inconsolata"
style = "Light"
