[font]
size = 12.0

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Light"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0
