[font]
size = 18.0

[font.bold]
family = "Monaspace Xenon"
style = "SemiBold"

[font.italic]
family = "Monaspace Krypton"
style = "Light"

[font.normal]
family = "Monaspace Neon"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0
