[alias]
b = "build"
c = "check"
t = "test"
r = "run"
rr = "run --release"

[cargo-new]
vcs = "git"

[term]
quiet = false
verbose = false

[target.aarch64-apple-darwin]
rustflags = "-lc++ -l framework=Accelerate"
